new worklow logic

diff --git a/.github/workflows/productionworkflow.yaml b/.github/workflows/productionworkflow.yaml
--- a/.github/workflows/productionworkflow.yaml
+++ b/.github/workflows/productionworkflow.yaml
@@ -36,10 +36,25 @@ jobs:
         id: deployment
         run: |
           python ./se_ml_production/ML_backend_GKE/ML_GKE/ML_Service_GKE/main.py
-          if grep -q "Deployment Test Complete with no errors" deployment.log; then
-            echo "Deployment Test Complete with no errors"
-            exit 0
-          else
-            echo "Deployment Test Failed"
-            exit 1
-          fi
+          
+          # Get the PID of the background process
+          APP_PID=$!
+
+          # Monitor the deployment log for the success message
+          while true; do
+            if grep -q "Deployment Test Complete with no errors" ./deployment.log; then
+              echo "Deployment Test Complete with no errors"
+              kill $APP_PID
+              exit 0
+            fi
+            sleep 1
+          done
+
+          # If the loop exits, it means the deployment failed
+          echo "Deployment Test Failed"
+          kill $APP_PID
+          exit 1
+
+
+
+         
